name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: "${APP_NETWORK_POOL}"

volumes:
  habitat-config:
  audiobookshelf-config:
  audiobookshelf-metadata:

secrets:
  AUDIOBOOKSHELF_ADMIN_PASSWORD:
    file: ${SECRETS_DIR}/AUDIOBOOKSHELF_ADMIN_PASSWORD
  AUDIOBOOKSHELF_OAUTH_CLIENT_ID:
    file: ${SECRETS_DIR}/AUDIOBOOKSHELF_OAUTH_CLIENT_ID
  AUDIOBOOKSHELF_OAUTH_CLIENT_SECRET:
    file: ${SECRETS_DIR}/AUDIOBOOKSHELF_OAUTH_CLIENT_SECRET
  AUDIOBOOKSHELF_OAUTH_CLIENT_SECRET_HASHED_PBKDF2:
    file: ${SECRETS_DIR}/AUDIOBOOKSHELF_OAUTH_CLIENT_SECRET_HASHED_PBKDF2


services:

  habitat-config-echo:
    image: tschebbischeff/habitat-config:latest
    container_name: ${APP_NAME_HOST}_habitat-config-echo
    restart: no
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/habitat-config.env
        required: false
    environment:
      MODULE_NAME: "echo"
    secrets:
      - AUDIOBOOKSHELF_OAUTH_CLIENT_ID
      - AUDIOBOOKSHELF_OAUTH_CLIENT_SECRET_HASHED_PBKDF2
    networks:
      internal:
    volumes:
      - habitat-config:/habitat-config/orchestration
      - ./habitat-config:/habitat-config/source:ro
      - audiobookshelf-config:/habitat-config/target/audiobookshelf

  audiobookshelf:
    build:
      context: ./audiobookshelf
    container_name: ${APP_NAME_HOST}_audiobookshelf
    restart: unless-stopped
    expose:
      - '80'
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/audiobookshelf.env
        required: false
    environment:
      SOURCE: 'docker'
      BACKUP_PATH: './backups'
      PORT: '80'
      AUDIOBOOKSHELF_ADMIN_PASSWORD_FILE: '/run/secrets/AUDIOBOOKSHELF_ADMIN_PASSWORD'
    secrets:
      - AUDIOBOOKSHELF_ADMIN_PASSWORD
      - AUDIOBOOKSHELF_OAUTH_CLIENT_ID
      - AUDIOBOOKSHELF_OAUTH_CLIENT_SECRET
    volumes:
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
      - ${VOLUME_DIR}/audiobookshelf-audiobooks:/audiobooks
      - ${VOLUME_DIR}/audiobookshelf-podcasts:/podcasts
      - ${VOLUME_DIR}/audiobookshelf-backups:/backups
    networks:
      internal:
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:80/healthcheck" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      habitat-config-echo:
        condition: service_completed_successfully
